#!/bin/bash

echo Cleaning...
rm -rf ./dist

if [ -z "$GIT_COMMIT" ]; then
  export GIT_COMMIT=$(git rev-parse HEAD)
  export GIT_URL=$(git config --get remote.origin.url)
fi

# Remove .git from url in order to get https link to repo (assumes https url for GitHub)
export GITHUB_URL=$(echo $GIT_URL | rev | cut -c 5- | rev | cut -c 5- | tr : / | awk '{print "https://"$1}')


echo Building app
npm run build

rc=$?
if [[ $rc != 0 ]] ; then
    echo "Npm build failed with exit code " $rc
    exit $rc
fi

mkdir dist
cat > ./dist/githash.txt <<_EOF_
$GIT_COMMIT
_EOF_

cat > ./dist/version.html << _EOF_
<!doctype html>
<head>
   <title>App version information</title>
</head>
<body>
   <span>Origin:</span> <span>$GITHUB_URL</span>
   <span>Revision:</span> <span>$GIT_COMMIT</span>
   <p>
   <div><a href="$GITHUB_URL/commits/$GIT_COMMIT">History of current version</a></div>
</body>
_EOF_


cp package.json ./build

echo Building docker image

docker build -t njallzzz/tictactoe:$GIT_COMMIT .
#docker build -t njallzzz/tictactoe .

rc=$?
if [[ $rc != 0 ]] ; then
    echo "Docker build failed " $rc
    exit $rc
fi

docker push njallzzz/tictactoe:$GIT_COMMIT
rc=$?
if [[ $rc != 0 ]] ; then
    echo "Docker push 1 failed " $rc
    exit $rc
fi

docker tag njallzzz/tictactoe:$GIT_COMMIT njallzzz/tictactoe:latest
docker push njallzzz/tictactoe:latest
rc=$?
if [[ $rc != 0 ]] ; then
    echo "Docker push 2 failed " $rc
    exit $rc
fi

echo "Done"
