#!/usr/bin/python
import subprocess
from time import sleep
import json

security_group = "webserver-perm"
pem = "microserver2"
image_id = "ami-9398d3e0"

pem_file = pem + ".pem"
ip = "54.194.155.230"
print "VM IP Address:", ip

command7 = ["scp", "-oStrictHostKeyChecking=no", "-i", pem_file, "vm-script-1", "ec2-user@"+ ip + ":/home/ec2-user"]
command8 = ["scp", "-oStrictHostKeyChecking=no", "-i", pem_file, "vm-script-2", "ec2-user@"+ ip + ":/home/ec2-user"]
command9 = ["ssh", "-oStrictHostKeyChecking=no", "-i", pem_file, "ec2-user@" + ip, "./vm-script-1"]
command10 = ["ssh", "-oStrictHostKeyChecking=no", "-i", pem_file, "ec2-user@" + ip, "./vm-script-2"]

process = subprocess.Popen(command7, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, error = process.communicate()
if output or error:
    print "Output:", output
    print "Error:", error

process = subprocess.Popen(command8, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, error = process.communicate()
if output or error:
    print "Output:", output
    print "Error:", error

process = subprocess.Popen(command9, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, error = process.communicate()
if output or error:
    print "Output:", output
    print "Error:", error

process = subprocess.Popen(command10, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, error = process.communicate()
if output or error:
    print "Output:", output
    print "Error:", error


